[package]
authors     = ["magic-akari <akari.ccino@gmail.com>"]
description = "A WASM based Lua Formatter"
edition     = "2024"
homepage    = "https://github.com/wasm-fmt/lua_fmt"
keywords    = ["wasm", "stylua", "lua", "formatter"]
license     = "MIT OR Apache-2.0"
name        = "lua_fmt"
readme      = "README.md"
repository  = "https://github.com/wasm-fmt/lua_fmt"
version     = "0.3.3"


[dependencies]
bridge = { package = "wasm-fmt-fdk", version = "=0.0.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
stylua = { version = "2.0.0", default-features = false, features = [
	"lua52",
	"lua53",
	"lua54",
] }


[lib]
crate-type = ["cdylib", "rlib"]


[profile.release]
codegen-units = 1
debug         = false
lto           = true
opt-level     = 2
panic         = "abort"
strip         = "symbols"

[patch.crates-io]
regex = { path = "crates/regex_patch" }
